In [1]:
import numpy as np
a = np.random.randint(1,100,15)
np.sort(a)
np.sort(a)[::-1]

array([99, 97, 89, 82, 70, 66, 53, 42, 38, 36, 30, 27, 20, 12,  4],
      dtype=int32)

In [2]:
#2d Array
b = np.random.randint(1,100,24).reshape(4,6)
c = np.sort(b,axis =0)
d = np.sort(b,axis =1)
print(c)
print(b)

[[60 29 21 28 44  6]
 [65 73 39 67 57 28]
 [66 73 49 78 74 62]
 [70 97 89 80 81 93]]
[[65 73 89 80 57 28]
 [66 29 49 28 81 62]
 [70 73 39 67 44 93]
 [60 97 21 78 74  6]]


In [7]:
#append
np.append(a,200)

array([ 32,   1,  78,  20,  36,  45,  66,  19,  76,  51,  78,  97,  72,
         2,  83, 200])

In [12]:
b = np.append(b, np.ones((b.shape[0], 1)), axis=1)
print(b)

[[29. 39. 12. 85. 17. 48.  1.]
 [20. 15. 70. 16. 67. 96.  1.]
 [92.  7. 10. 62.  2. 46.  1.]
 [16. 83. 93. 91.  6. 67.  1.]]


In [3]:
c= np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [4]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [6]:
#np.unique()
e = np.array([1,2,2,3,4,4,4,4,5,5,1,1,7,7,90])
np.unique(e)

array([ 1,  2,  3,  4,  5,  7, 90])

In [4]:
f = np.random.randint(1,40,10)
f
np.where(f>10)

(array([0, 2, 3, 4, 6, 7, 8, 9]),)

In [12]:
np.where(f<15,0,f)

array([ 0, 34,  0,  0, 25, 19, 26,  0, 17,  0], dtype=int32)

In [14]:
#argMax
f
np.argmax(f)

np.int64(1)

In [8]:
a = np.arange(12).reshape(3,4)

In [17]:
np.argmax(a,axis=0)

array([2, 2, 2, 2])

In [18]:
np.argmax(a,axis=1)

array([3, 3, 3])

In [6]:
f
np.cumsum(f)

array([ 27,  30,  64,  84, 115, 119, 156, 169, 202, 241])

In [ ]:
#2d
a
np.cumsum(a,axis=0)# column wise

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [ ]:
np.cumsum(a,axis=1)#row wise

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [14]:
#Cumulative Product:-
np.cumprod(f)

array([           27,            81,          2754,         55080,
             1707480,       6829920,     252707040,    3285191520,
        108411320160, 4228041486240])

In [20]:

print(f)
print(np.percentile(f,50))

[27  3 34 20 31  4 37 13 33 39]
29.0


In [ ]:
a = np.random.randint(1,100,20)
print(a)
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])
#gives the data of histogram

[61 35 76 90 78 46 81 70 41 62  4 32 66 16 13 36 69 54 45 59]


(array([1, 2, 0, 3, 3, 2, 4, 3, 1, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [26]:
salary = np.array([100,200,400,500,600])
exp = np.array([2,5,6,6,8])

np.corrcoef(salary,exp)

array([[1.        , 0.92447345],
       [0.92447345, 1.        ]])

In [32]:
a= np.random.randint(1,40,15)
print(a)
items=[2,401,23,45,67,78,19,20]
np.isin(a,items)


[13 14 11 15 16 12 10  6 20 33  2 22 23 32 38]


array([False, False, False, False, False, False, False, False,  True,
       False,  True, False,  True, False, False])

In [33]:
np.put(a,[0,3],[12,34400])
print(a)

[   12    14    11 34400    16    12    10     6    20    33     2    22
    23    32    38]


#Set Functions:-

In [37]:
x = np.array([1,2,3,4,56,67])
y = np.array([2,3,4,5,6,7,8])

print(np.union1d(x,y))
print(np.intersect1d(x,y))
print(np.setdiff1d(x,y))
print(np.setxor1d(x,y))

[ 1  2  3  4  5  6  7  8 56 67]
[2 3 4]
[ 1 56 67]
[ 1  5  6  7  8 56 67]


In [38]:
a = np.random.randint(1,400,30)
print(a)
np.clip(a,a_max=200,a_min=50)


[ 19 316 378 228  31 330 314 138 105 279 164  53 132 185 105 393 267 120
 233 362 185  49 334 351 121 165 203  41 386  23]


array([ 50, 200, 200, 200,  50, 200, 200, 138, 105, 200, 164,  53, 132,
       185, 105, 200, 200, 120, 200, 200, 185,  50, 200, 200, 121, 165,
       200,  50, 200,  50], dtype=int32)