#Numpy Arrays Vs Python Sequences
NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

#Creating Numpy Arrays:-


In [3]:
import numpy as np
print(5)
a = np.array([1,2,3])
print(a)
print(type(a))


5
[1 2 3]
<class 'numpy.ndarray'>


In [4]:
#2d Array
b = np.array([[12,12,89],[2,3,4]])
print(b)

[[12 12 89]
 [ 2  3  4]]


In [12]:
#d-type
d=np.array([2,3,4],dtype=float)
print(d)
c=np.array([2,3,4],dtype=bool)
print(c)
np.array([2,0,4],dtype=bool)
np.array([2,0,4],dtype=complex)

[2. 3. 4.]
[ True  True  True]


array([2.+0.j, 0.+0.j, 4.+0.j])

In [14]:
#np.arrange

np.arange(1,34,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31])

In [16]:
np.arange(1,21).reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [18]:
np.random.random((3,4))

array([[0.66700874, 0.52098334, 0.17178841, 0.21898046],
       [0.21303457, 0.36269053, 0.92702234, 0.13208831],
       [0.32920691, 0.07374951, 0.68301149, 0.0829903 ]])

In [19]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

In [5]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#Array Attributes

In [24]:
a1= np.arange(10)
a2= np.arange(15).reshape(3,5)
a3= np.arange(8).reshape(2,2,2)

a1.ndim
a2.ndim

2

In [31]:
#shape
a3= np.arange(8,dtype=np.int32).reshape(2,2,2)
a3.shape
a2= np.arange(15).reshape(3,5)
a2.shape

print(a3.size)
print(a3.itemsize)
print(a2.dtype)
print(a3.dtype)

8
4
int64
int32


In [32]:
#changing dtype
a3= np.arange(8,dtype=np.int32).reshape(2,2,2)
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

#Array Operations:-


In [37]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

print(a2**2)

#relational
print(a2>5)

[[144 169 196 225]
 [256 289 324 361]
 [400 441 484 529]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [38]:
#Vector Operations:-
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1+a2


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

#Array Functions:-


In [6]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)

# print(np.max(a1))
# print(np.sum(a1))
# print(np.min(a1))

# 0 -> col 1-> row
np.max(a1,axis=1)

#mean
np.mean(a1)

np.dot(a1,a2)
a1=np.arange(24).reshape(4,6)
a1[::3,::5]




array([[ 0,  5],
       [18, 23]])

#Iteration

In [11]:
a1=np.arange(27).reshape(3,3,3)
a1

for i in a1:
    print(i)
    print("HELLO")

for i in np.nditer(a1):
    print(i)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
HELLO
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
HELLO
[[18 19 20]
 [21 22 23]
 [24 25 26]]
HELLO
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


#Reshaping:-

In [13]:
#reshape

#transpose:-
a1=np.arange(27).reshape(3,9)
print(a1)
a2=np.transpose(a1)
print(a2)



[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]
[[ 0  9 18]
 [ 1 10 19]
 [ 2 11 20]
 [ 3 12 21]
 [ 4 13 22]
 [ 5 14 23]
 [ 6 15 24]
 [ 7 16 25]
 [ 8 17 26]]


In [14]:
#ravel:-
a1=np.arange(27).reshape(3,9)
print(a2.ravel())


[ 0  9 18  1 10 19  2 11 20  3 12 21  4 13 22  5 14 23  6 15 24  7 16 25
  8 17 26]


#Stacking:-

In [18]:
#horizontal Stacking:-
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

np.hstack((a1,a2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [19]:
#vertical Stacking:-
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

np.vstack((a1,a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#Splitting:-

In [20]:
#hsplit:-
a2 = np.arange(12,24).reshape(3,4)
np.hsplit(a2,2)


[array([[12, 13],
        [16, 17],
        [20, 21]]),
 array([[14, 15],
        [18, 19],
        [22, 23]])]

In [22]:
#vsplit:-
a2 = np.arange(12,24).reshape(3,4)
np.vsplit(a2,3)


[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]